### PR TITLE
Handle BotActions in a queue

### LINKED ISSUE #20: Implement queue system to handle multiple check requests
As title.

For now, have the code execute in series, queuing each request in turn.

### PR DESCRIPTION
**Pull request by FraserGreenroyd**
Fixes #20

### CODE REVIEW

**Comment by FraserGreenroyd** [comment]
BHoMBot run check core

**Comment by FraserGreenroyd** [comment]
BHoMBot run check core

**Comment by FraserGreenroyd** [comment]
BHoMBot run check core

**Comment by IsakNaslundBh** [comment]
bhombot run check core

**Comment by IsakNaslundBh** [comment]
BHoMBot run check core

**Comment by IsakNaslundBh** [comment]
BHoMbot why dont you love me? 😢

**Comment by FraserGreenroyd** [comment]
Because BHoMBot wasn't turned on :smile: try again @IsakNaslundBh

**Comment by IsakNaslundBh** [comment]
bhombot run check core

**Comment by IsakNaslundBh** [comment]
BHoMBot run check core

**Comment by IsakNaslundBh** [comment]
bhombot run check core

**Comment by IsakNaslundBh** [comment]
BHoMBot RUN CHECK CORE

**Comment by IsakNaslundBh** [comment]
BHoMBot run check core

**Comment by IsakNaslundBh** [comment]
bhomboT rUN cHecK cORE

**Comment by IsakNaslundBh** [comment]
bhombot run check core

**Comment by IsakNaslundBh** [comment]
bhombot run check core

**Comment by FraserGreenroyd** [comment]
BHoMBot run check core

**Pull request merged**
