### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by FraserGreenroyd**
Testing triggering BHoMBot

### CODE REVIEW

**Comment by FraserGreenroyd** [comment]
BHoMBot run check core

**Comment by FraserGreenroyd** [comment]
@BHoMBot run check core

**Comment by al-fisher** [comment]
@BHoMBot run check core please

**Comment by al-fisher** [comment]
@BHoMBot testing random text

**Comment by FraserGreenroyd** [comment]
Thanks @BHoMBot !

**Comment by FraserGreenroyd** [comment]
As this PR is not really needed I am now closing and deleting the branch :smile:

**Pull request closed without merging**
