### PR TITLE
Auto fixing cs project files

### LINKED ISSUE #6: Add ability to fix CSProj issues
If CSProj issues exist following the check in #5 then provide an option to fix it automatically.

### PR DESCRIPTION
**Pull request by FraserGreenroyd**
Fixes #6

### CODE REVIEW

**Comment by FraserGreenroyd** [comment]
@BHoMBot run check project compliance

**Comment by FraserGreenroyd** [comment]
@BHoMBot run check project compliance

**Comment by FraserGreenroyd** [comment]
@BHoMBot run check project compliance

**Comment by FraserGreenroyd** [comment]
@BHoMBot run check project compliance

**Comment by FraserGreenroyd** [comment]
@BHoMBot run check core

**Comment by FraserGreenroyd** [comment]
@BHoMBot run check project compliance

**Comment by FraserGreenroyd** [comment]
@BHoMBot fix project file

**Comment by FraserGreenroyd** [comment]
@BHoMBot fix project file

**Comment by FraserGreenroyd** [comment]
@BHoMBot fix project file

**Comment by IsakNaslundBh** [comment]
@BHoMBot fix project file

**Comment by IsakNaslundBh** [comment]
@BHoMBot ok, thanks, that makes sense!

**Comment by FraserGreenroyd** [comment]
@BHoMBot run check core

**Comment by FraserGreenroyd** [comment]
@BHoMBot run check project compliance

**Comment by FraserGreenroyd** [comment]
@BHoMBot run check project compliance

**Comment by FraserGreenroyd** [comment]
@BHoMBot fix project file

**Comment by FraserGreenroyd** [comment]
@BHoMBot fix project file

**Comment by FraserGreenroyd** [comment]
@BHoMBot fix project file

**Comment by FraserGreenroyd** [comment]
@BHoMBot fix project file

**Comment by FraserGreenroyd** [comment]
@BHoMBot fix project file

**Comment by FraserGreenroyd** [comment]
@BHoMBot fix project file

**Comment by FraserGreenroyd** [comment]
@BHoMBot fix project file

**Comment by FraserGreenroyd** [comment]
@BHoMBot fix project file

**Comment by FraserGreenroyd** [comment]
@BHoMBot run check project compliance

**Comment by FraserGreenroyd** [comment]
@BHoMBot run check project compliance

**Comment by FraserGreenroyd** [comment]
@BHoMBot run check project compliance

**Comment by FraserGreenroyd** [comment]
@BHoMBot run check project compliance

**Comment by FraserGreenroyd** [comment]
@BHoMBot fix project file

**Comment by FraserGreenroyd** [comment]
@BHoMBot run check project compliance

**Comment by FraserGreenroyd** [comment]
@BHoMBot run check project compliance

**Comment by FraserGreenroyd** [comment]
@BHoMBot fix project file

**Comment by FraserGreenroyd** [comment]
@BHoMBot fix project file

**Comment by FraserGreenroyd** [comment]
@BHoMBot fix project file

**Comment by FraserGreenroyd** [comment]
@BHoMBot run check project compliance

**Comment by FraserGreenroyd** [comment]
@BHoMBot run check core

**Comment by FraserGreenroyd** [comment]
@BHoMBot run check project compliance

**Comment by FraserGreenroyd** [comment]
@BHoMBot run check project compliance

**Comment by FraserGreenroyd** [comment]
@BHoMBot run check project compliance

**Comment by FraserGreenroyd** [comment]
@BHoMBot run check project compliance

**Comment by FraserGreenroyd** [comment]
@BHoMBot run check project compliance

**Comment by FraserGreenroyd** [comment]
@BHoMBot run check project compliance

**Comment by FraserGreenroyd** [comment]
@BHoMBot run check project compliance

**Comment by FraserGreenroyd** [comment]
@BHoMBot run check project compliance

**Comment by FraserGreenroyd** [comment]
@BHoMBot run check project compliance

**Comment by FraserGreenroyd** [comment]
@BHoMBot run check project compliance

**Comment by FraserGreenroyd** [comment]
@BHoMBot run check project compliance

**Comment by FraserGreenroyd** [comment]
@BHoMBot fix project file

**Comment by FraserGreenroyd** [comment]
@BHoMBot run check project compliance

**Comment by FraserGreenroyd** [comment]
@BHoMBot run check core

**Comment by FraserGreenroyd** [comment]
@BHoMBot run check core

**Comment by FraserGreenroyd** [comment]
@BHoMBot run check project compliance

**Comment by FraserGreenroyd** [comment]
@BHoMBot run check core

**Comment by FraserGreenroyd** [comment]
@BHoMBot run check project compliance

**Comment by FraserGreenroyd** [comment]
@BHoMBot I am authorising dispensation to be granted on check 1036405693

**Comment by FraserGreenroyd** [comment]
@BHoMBot I am authorising dispensation to be granted on check 1036405693

**Comment by FraserGreenroyd** [comment]
@BHoMBot I am authorising dispensation to be granted on check 1036405693

**Comment by FraserGreenroyd** [comment]
@BHoMBot I am authorising dispensation to be granted on check 1036405693

**Comment by FraserGreenroyd** [comment]
@BHoMBot run check project compliance

**Comment by FraserGreenroyd** [comment]
@BHoMBot run check core

**Comment by FraserGreenroyd** [comment]
@BHoMBot I am authorising dispensation to be granted on check 1036688927

**Comment by FraserGreenroyd** [comment]
@BHoMBot run check project compliance

**Comment by FraserGreenroyd** [comment]
@BHoMBot I am authorising dispensation to be granted on check 1036712461

**Comment by FraserGreenroyd** [comment]
@BHoMBot this is a CI/CD instruction. I am authorising dispensation to be granted on check 1036712461

**Comment by FraserGreenroyd** [comment]
@BHoMBot this is a CI/CD instruction. I am authorising dispensation to be granted on check ref. 1036712461

**Comment by FraserGreenroyd** [comment]
@BHoMBot run check core

**Pull request merged**
